### ISSUE TITLE
custom arguments don't work

### ISSUE THREAD

**Issue by X-G** [idleberg/atom-build-python#4]
I try to change the arguments in the package setting. It turns out that no matter what you input, the arguments always `-u`.
I tried both on Windows 7 & Ubuntu. The same issue.

**Comment by idleberg** [comment]
You have to choose the target _Python (user)_ in order to use the custom arguments. I have to admit this isn't clear at all and should be communicated better in a future release!

**Comment by X-G** [comment]
Thanks for your quick reply. Now I know how to do that.
