### ISSUE TITLE
feature request: customize Python name 

### ISSUE THREAD

**Issue by X-G** [idleberg/atom-build-python#5]
Some software have built-in Python environment. For example, Abaqus is a finite element analysis software, which has Python embedded as a scripting language. One can run the Python code by using 
```
abaqus cae -nogui xxx.py
```
`abaqus` is the command in system's path. `cae` is an argument indicate starting the Abaqus'  preprocessing and post processing module. `-nogui` is an argument indicate don't start the GUI of `cae`. `xxx.py` is the python code.
If this package allow to customize the name of python, It would allow run python code using software built-in Python environment.

**Comment by idleberg** [comment]
Interesting. I've added a custom interpreter option in the `master`, would you mind giving it a try before I release it?

**Comment by X-G** [comment]
Good job! I tried the custom interpreter option, it works.
I just  have a minor recommendation on the package setting interface. It may be more logical if put `customInterpreter` above `customArguments`. Because both `pythonVersion` and `customInterpreter` are options with regard to the interpreter, normally in the front of a command. `customArguments` is options about arguments, normally after the name of interpreter. 
Many thanks for this excellent package.
