### ISSUE TITLE
Strange unicode support while using python 3

### ISSUE THREAD

**Issue by MrYann** [idleberg/atom-build-python#6]
Hi.
The python "build" command is somehow different than the shell python : 

Minimal example : 
```
with open("test.txt", "w") as file:
    file.write("é")
```

With atom build python, i get UnicodeEncodeError.
With python in shell, no error.

Of course, adding "encoding='utf-8'" to the open statement tackles the problem ; but with python 3 it should not be needed.

For reference, i use a mac with latest macOS and have python 3.5.2, anaconda distribution.

**Comment by MrYann** [comment]
In fact, it seems like the whole process is unicode unfriendly : 
When the python file has unicode name, the filename in the error reports is not decoded properly.

Even more so, launching an external process within the python code, through subprocess.call, provides a wrong python environment to the subprocess (resulting in UnicodeDecodeError errors for the called process)

**Comment by idleberg** [comment]
Unless this can be solved with a flag for `python`, this should probably be addressed in the [`build`](https://github.com/noseglid/atom-build) package and not in this provider for the said package.

**Comment by MrYann** [comment]
Ok. I have tried some flags without success. So I will get in touch with the "build" guys. Thanks.
