### ISSUE TITLE
problem of custom interpreter 

### ISSUE THREAD

**Issue by X-G** [idleberg/atom-build-python#7]
Hi,

Since you add the support for `custom interpreter` functionality after issue #5 , I use it a lot and it really saves my time. Many thanks to you.

Recently, I have a small project and need use the system build-in Python environment. So I change the active target from `Python (user)` to `Python`.  But I found there is a problem when I switch it back.
Normally, my `custom interpreter` is `abaqus`. The `custom arguments` is `cae -nogui`. When I use abaqus Python interpreter, I select the active target as `Python (user)` and code will be built by
```
abaqus cae -nogui xxx.py
```
When I want to use system build-in Python, I select active targets as `Python` and code will be built by
```
abaqus -u xxx.py
```
Actually what I want is 
```
python -u xxx.py
```

So I think instead of let the `custom interpreter` override the `Python version` option,  it's better that the `custom interpreter` option only works with `Python (user)`  target. This strategy is consistent with `custom arguments`. In my situation, `abaqus` don't have the argument  `-u` at all. So I think maybe it will make things clear that both `custom interpreter` and `custom arguments` options only work with `Python (user)` target.

**Comment by idleberg** [comment]
Please give the current master a shot before I publish the changes.

Also, I wanted to mention you that you can assign different keyboard shortcuts for different build commands.

**Example:**

```cson
'atom-text-editor':
  'cmd-alt-a': 'python:compile-script'
  'cmd-alt-b': 'python:compile-with-user-settings'
```

However, I think I'm going to add a default shortcut for `Python (user)` anyway

**Comment by X-G** [comment]
It works well for me. Looking forward to the new version.
